site_name: jawm
site_description: Just Another Workflow Manager — lightweight, Python-native workflow orchestration.
repo_name: mpg-age-bioinformatics/jawm
repo_url: https://github.com/mpg-age-bioinformatics/jawm
site_url: https://bioinformatics.age.mpg.de/jawm/
edit_uri: edit/main/docs/

theme:
  name: material
  # name: readthedocs
  logo: assets/jawm-logo.png
  favicon: assets/jawm-icon.png
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true

extra_css:
  - stylesheets/style.css

nav:
  - Home: index.md
  - Getting Started:
    - Installation: get_started/install.md
    - Your First Process: get_started/run_process.md
    - Running a Workflow: get_started/run_workflow.md
    - Developing a Workflow: get_started/develop_workflow.md
  - Process: 
    - Overview: process/overview.md
    - Configuration & Precedence: process/conf_precedence.md
    - Parameters: process/parameters.md
    - Class-Level Parameters: process/cls_parameters.md
    - Methods: process/methods.md
    - Class-Level Methods: process/cls_methods.md
  - YAML & Configuration:
    - Overview: config/overview.md
    - YAML Config: config/yaml.md
    - JAWM Variable Config: config/config.md
  - Utils: utils.md
  - Module:
    - Overview: module/overview.md
    - Run a Module: module/run.md
    - Load Modules in Workflow: module/load.md
    - Develop a Module: module/develop.md
  - CLI Tools: cli-tools.md
  - Examples & Use Cases: examples.md
  - How-To Guides: howto.md
  - Testing: testing.md
  - Advanced Development: development.md
  - Version Log: version-log.md
  - Support: support.md